name: Monitor Metrô SP

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_metro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install selenium pandas requests webdriver-manager

      - name: Executar Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commitar mudanças
        run: |
          git config --global user.name 'MetroBot'
          git config --global user.email 'bot@metro.sp'
          
          # Adiciona o JSON (se existir)
          if [ -f estado_metro.json ]; then
            git add estado_metro.json
          fi

          # Adiciona o CSV (se existir)
          if [ -f historico_ocorrencias.csv ]; then
            git add historico_ocorrencias.csv
          fi
          
          # Verifica se há algo 'staged' para commitar
          if ! git diff --cached --quiet; then
            git commit -m "Atualizando dados e histórico"
            git push
          else
            echo "Nenhuma alteração para salvar."
          fi
