name: Monitor Metrô SP

on:
  schedule:
    - cron: '*/5 * * * *' # Roda a cada 5 minutos
  workflow_dispatch: # Permite rodar manualmente para testar

permissions:
  contents: write # Permissão CRUCIAL para salvar o arquivo JSON

jobs:
  check_metro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install selenium pandas requests webdriver-manager

      - name: Executar Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commitar mudanças (se houver atualização)
        run: |
          git config --global user.name 'MetroBot'
          git config --global user.email 'bot@metro.sp'
          # Adiciona o arquivo de estado
          git add estado_metro.json
          # Só faz commit se houver mudança no arquivo (evita erro de commit vazio)
          git diff --quiet && git diff --staged --quiet || (git commit -m "Atualizando status linhas" && git push)
