name: Monitor Metrô SP

on:
  schedule:
    - cron: '*/5 * * * *' # Executa a cada 5 minutos
  workflow_dispatch: # Botão manual para testes

permissions:
  contents: write

jobs:
  check_metro:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install selenium pandas requests webdriver-manager

      - name: Executar Scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commitar mudanças
        run: |
          git config --global user.name 'MetroBot'
          git config --global user.email 'bot@metro.sp'
          
          # Verifica se o arquivo existe antes de tentar adicionar
          if [ -f estado_metro.json ]; then
            git add estado_metro.json
            # Só faz commit se houver diferença real
            git diff --quiet && git diff --staged --quiet || (git commit -m "Atualizando status linhas" && git push)
          else
            echo "Aviso: O arquivo estado_metro.json não foi gerado nesta execução."
          fi
